Tech 7764 change user fields to use full name
industrydive/sourcedive pull request #41
Opened 2020-03-09 13:31 UTC by eric38383

[TECH-<id> <name here>](https://industrydive.atlassian.net/browse/TECH-<id>)

### Non-technical Context

This merge will displayed the User's first and last name in the Interaction and Sources Admin instead of the User's username.

### Technical Context

- Create custom admin methods for displaying created by field. 
- Change interviewers_listview to use full name. 
- Overwrite form field for many to many method in Interaction Admin.
- Create InterviewerChoice class to overwrite label from instance to display user's full name.

### Reproduction Steps

- [ ] Login to admin for sourcedive.
- [ ] Go to source list view. Created by column should display username.
- [ ] Go to sources change page and open advanced info. Created by field should display username. Also attempt to add a new interaction on the same page below. Interviewer selects should display username.
- [ ] Go to interaction list view. Created by and interviewer(s) column should display username.
- [ ] Go to interaction add page. Select dropdown for interviewer(s) should display username.
- [ ] Go to interaction change page. Repeat above step. Created by field should also display username.

### Manual Testing Instructions

Repeat the reproduction steps, except User's first and last name should appear instead of user' username.

- [ ] Login to admin for sourcedive.
- [ ] Go to source list view. Created by column should display user's first and last name.
- [ ] Go to sources change page and open advanced info. Created by field should display user's first and last name. Also attempt to add a new interaction on the same page below. Interviewer selects should display user's first and last name.
- [ ] Go to interaction list view. Created by and interviewer(s) column should display user's first and last name.
- [ ] Go to interaction add page. Select dropdown for interviewer(s) should display user's first and last name.
- [ ] Go to interaction change page. Repeat above step. Created by field should also display user's first and last name.

### QA Checklist

#### Developer

- [X] Ensure code complies with the [style guide](https://industrydive.atlassian.net/wiki/spaces/TECH/pages/639500407/Tech+Team+s+Style+Guides)
- [X] Devise edge cases to test the bug fix or feature being merged
- [X] Make sure the code is clean and understandable
- [X] Ensure code is not overly inefficient
- [X] Ensure documentation is understandable and accurate, including:
    - [X] Code comments and doc strings
    - [X] Technical documentation

#### Reviewer

- [ ] Ensure code complies with the [style guide](https://industrydive.atlassian.net/wiki/spaces/TECH/pages/639500407/Tech+Team+s+Style+Guides)
    - If there are few or minor issues, add inline GitHub comments
    - If there are many issues or it seems like the developer did not follow the style guide, leave a comment asking them to do so
- [ ] Devise edge cases to test the bug fix or feature being merged
- [ ] Make sure the code is clean and understandable
    - [ ] Ask for inline comments on unclear sections
- [ ] Ensure code is not overly inefficient
- [ ] Ensure documentation is understandable and accurate, including:
    - [ ] Code comments and doc strings
    - [ ] Technical documentation

2020-03-09 20:09 UTC, greglinch commented
@eric38383 Thanks for doing this! One quick update needed, which is my fault for not specifying in the ticket description, is that we still need `get_username()` as a fallback if there's no value for `get_full_name()`. 

Also, I got this on the interaction list view:

<img width="607" alt="Screen Shot 2020-03-09 at 3 56 42 PM" src="https://user-images.githubusercontent.com/327783/76252897-0294c080-6220-11ea-9ee8-0970cb635a20.png">

2020-03-09 20:19 UTC, eric38383 commented
Ok cool, will take a look at that!

2020-03-10 13:01 UTC, eric38383 commented
@greglinch Wasn't able to duplicate your error. I probably need to fill up my db a little more with some stuff. will investigate further when i get chance

2020-03-10 15:54 UTC, greglinch commented
@eric38383 Ah, ok. I just shared a Google Drive folder with data you can load to your local version.

2020-03-12 15:21 UTC, eric38383 commented
@greglinch Updated Dive add and change pages well. Created fallback if full name is missing on all forms. Created a helper function as well, not sure how you prefer to organize that, I could use some guidance.

On the error, it seems that `Interaction.objects.get(pk=4)`  has a null for created_by field. Let me know how best to proceed here.

2020-03-12 17:23 UTC, greglinch requested changes
@eric38383 Thanks for the updates! I fixed my local db to populate that field, so I'm all good now on errors.

2020-03-12 17:23 UTC, greglinch commented on sources/admin.py
> +def get_username(obj):
How about this for clarity?
```suggestion
def get_user_display_name(obj):
```

2020-03-12 17:23 UTC, greglinch commented on sources/admin.py
> +        return get_username(obj)
```suggestion
        return get_user_display_name(obj)
```

2020-03-12 17:23 UTC, greglinch commented on sources/admin.py
> +        interviewers = [get_username(interviewer) for interviewer in interviewers_list]
```suggestion
        interviewers = [get_user_display_name(interviewer) for interviewer in interviewers_list]
```

2020-03-12 17:23 UTC, greglinch commented on sources/admin.py
> +        return get_username(obj.created_by)
```suggestion
        return get_user_display_name(obj.created_by)
```

2020-03-12 18:29 UTC, eric38383 commented
updated with new function name

2020-04-08 20:26 UTC, greglinch commented
@eric38383 Sorry it took so long to approve this. All good!

2020-04-08 20:26 UTC, merged